version: '3.4'
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - 8083:8083
      - 8082:8082
      - 8081:8081
    volumes:
      - ./data:/nexus-data:z

  nginx-proxy:
    image: nginx
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/ssl:ro

  


